version: "3.9"

services:
  django_app:
    build: .
    container_name: django_app
    command: >
      sh -c "until mysqladmin ping -h db -uroot -proot --silent; do
               echo 'Waiting for MySQL...'; sleep 2;
             done &&
             python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - django_app

volumes:
  mysql_data:
  static_volume:
